### ISSUE TITLE
.deb package does not contain systemd unit file

### ISSUE THREAD

**Issue by magnuslarsen** [rivosinc/prometheus-slurm-exporter#102]
Hello! Thanks for your great work

I've just downloaded the 1.6.6 release (using the newly added .deb package  https://github.com/rivosinc/prometheus-slurm-exporter/pull/97)

It claims to use systemd by default:
> You can download RPM or DEB versions from the [Releases](releases/) tab. The
packages are configured to use systemd to start and stop the service.

Which is nice, but the unit file doesn't seem to be included:
```sh
$ wget https://github.com/rivosinc/prometheus-slurm-exporter/releases/download/v1.6.6/prometheus-slurm-exporter_1.6.6_linux_amd64.deb

$ dpkg -c prometheus-slurm-exporter_1.6.6_linux_amd64.deb
drwxr-xr-x root/root         0 2024-09-15 06:59 ./usr/
drwxr-xr-x root/root         0 2024-09-15 06:59 ./usr/bin/
-rwxr-xr-x root/root   9588996 2024-09-15 06:59 ./usr/bin/prometheus-slurm-exporter
drwxr-xr-x root/root         0 2024-09-15 07:00 ./usr/share/
drwxr-xr-x root/root         0 2024-09-15 07:00 ./usr/share/prometheus-slurm-exporter/
drwxr-xr-x root/root         0 2024-09-15 07:00 ./usr/share/prometheus-slurm-exporter/templates/
-rw-r--r-- root/root       927 2024-09-15 06:59 ./usr/share/prometheus-slurm-exporter/templates/proc_traces.html

$
```

**Comment by abhinavDhulipala** [comment]
Howdy! Thanks for leaving a comment and catching that. We initially had systemd enabled by default, but decided to go without it by default. Here is the [context](https://github.com/rivosinc/prometheus-slurm-exporter/pull/97#pullrequestreview-2267137250) as to why. In short, I use containers for development, testing, and deployment and it was cumbersome to use it in that capacity. We also have a lot of ways to deploy the exporter and I didn't want to make that choice for the user. We compromised by providing the docs and a template for systemd deployment. I'll fix 
the readme :)

**Comment by magnuslarsen** [comment]
Ah perfect! Sorry for the confusion :-)
