### ISSUE TITLE
Label metrics with compute node features

### ISSUE THREAD

**Issue by fluidnumericsJoe** [rivosinc/prometheus-slurm-exporter#40]
Great project - so good to see this effort revived.

I have a cluster with only a few compute partitions, but we use features to label different GPU types that are made available and so that they can be requested using the `--constraint` flag during job submission. I'm looking to make a dashboard visualization that can show the job count over time segregated by the partition and the compute node features.

Do you have suggestions / ideas on what would be needed to accomplish this ? I'm willing to help implement and contribute code changes with a bit of guidance on where you'd start .

**Comment by abhinavDhulipala** [comment]
Course happy to add features! Now do you use the `--json` output or are you using the cli-fallback?

**Comment by fluidnumericsJoe** [comment]
I use the `--json` output with Slurm 23.0.2

**Comment by abhinavDhulipala** [comment]
Could you post some json as an example (no ip please) ?  Also what's the typical cardinality here. Can we simply add this as a label? Or we could simply sum over constraints as their own metrics. Those are our easiest options and in terms of query efficiency, specialized metrics that aggregate per constraints ( much like our Partition metrics) are probably our best bet. If we try to stuff multiple constraints into a single label, then queries would require regex which i try to avoid as much as possible. Let me know what you think.

**Comment by fluidnumericsJoe** [comment]
@abhinavDhulipala - Apologies for the delayed response here. I've attached an example json here.
With this version of Slurm (23.02.2), `features` is a string with each feature separated by `&`, e.g.
```
"features": "a100-80gb&preemptible&gpu-1"
```
I would think that we could just add these as labels.
[squeue.json](https://github.com/rivosinc/prometheus-slurm-exporter/files/14055978/squeue.json)

**Comment by abhinavDhulipala** [comment]
Just added an MR that should cover it. Please test it out and lmk if it works

**Comment by fluidnumericsJoe** [comment]
Thanks! Can do. I'll get this set up this week and get back to you.
