### ISSUE TITLE
Mem usage of 0 causes job parsing failure

### ISSUE THREAD

**Issue by coderforlife** [rivosinc/prometheus-slurm-exporter#56]
I am getting error messages like the following:

```
time=2024-02-01T02:02:01.503Z level=ERROR msg="job failed to parse with \"mem string 0 doesn't match regex ^(?P<num>([0-9]*[.])?[0-9]+)(?P<memunit>G|M|T)$\""
```

The output of squeue with the fallback command line is:
```
{"a": "pcdefault", "id": 210, "end_time": "2024-02-01T01:57:50", "u": "rocky", "state": "COMPLETED", "p": "compute", "cpu": 1, "mem": "0"}
{"a": "pcdefault", "id": 211, "end_time": "2024-02-01T05:57:23", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 212, "end_time": "2024-02-01T06:00:48", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 213, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 214, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 215, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 216, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 217, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 218, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 219, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 220, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 221, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 222, "end_time": "2024-02-01T06:01:04", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 223, "end_time": "2024-02-01T06:01:07", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 224, "end_time": "2024-02-01T06:01:07", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 225, "end_time": "2024-02-01T06:01:07", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
{"a": "pcdefault", "id": 226, "end_time": "2024-02-01T06:01:14", "u": "rocky", "state": "RUNNING", "p": "compute", "cpu": 1, "mem": "1G"}
```

It seems that only `COMPLETED` jobs are being shown with 0 mem usage. So as long as there is a COMPLETED job, all jobs further down the list won't be included. Maybe it would be better to just skip the one that fails to parse instead of skipping it and all ones after it?

**Comment by abhinavDhulipala** [comment]
Hi thanks for filing an issue!

I'm pretty sure I fixed that same issue in #33. What version of the exporter are you running?

Could you try `go install github.com/rivosinc/prometheus-slurm-exporter@v1.0.1`

**Comment by abhinavDhulipala** [comment]
It seems like these [lines](https://github.com/rivosinc/prometheus-slurm-exporter/blob/main/exporter/utils.go#L169-L171) should take care of the zero mem string. I will change the behavior to skip on parse fail though, thanks for the suggestion.

**Comment by coderforlife** [comment]
I was switching between latest and v1.0.1 and can't remember which I ended on. Seems like both should have had it fixed? I will intentionally try with v1.0.1 and see how it goes.

**Comment by abhinavDhulipala** [comment]
I think you are using an old version of the exporter. In the latest version, the error message reads [differently](https://github.com/rivosinc/prometheus-slurm-exporter/blob/main/exporter/utils.go#L180). Please update to the latest. Feel free to reopen if the bug still occurs

**Comment by coderforlife** [comment]
I have confirmed, on a fresh box, that when I install with

```
GOBIN=/usr/local/bin go install github.com/rivosinc/prometheus-slurm-exporter@v1.0.1
```

I get the error message `ERROR msg="job failed to parse with \"mem string 0 doesn't match regex ^(?P<num>([0-9]*[.])?[0-9]+)(?P<memunit>G|M|T)$\"` in the system logs.

I agree that the error message does not match. However, looking at the commit history, that change showed up in v1.1.1. I have explicitly installed that version. It seems to be working now, however, the 0-mem thing doesn't always show up for completed jobs. I will reopen if it shows up as a problem again.

**Comment by abhinavDhulipala** [comment]
Yeah, I definitely should've released more often. Not surprised that v1.0.1 was greatly diverged from latest. Sorry about that.
