### ISSUE TITLE
Job stats has no data

### ISSUE THREAD

**Issue by liu-shaobo** [rivosinc/prometheus-slurm-exporter#59]
### Environment
```Markdown
- OS: Ubunut 20.04.6
- Scheduler: Slurm 21.08.3
- grafana: 10.2.2
```
hi，why does the job stats have no data? node data is normal。run as follows:
```prometheus-slurm-exporter -slurm.cli-fallback```
<img width="1359" alt="image" src="https://github.com/rivosinc/prometheus-slurm-exporter/assets/6166167/3a703ce0-54ad-4709-b06a-87db109a95f7">

**Comment by abhinavDhulipala** [comment]
Hi, thanks for filing an issue. Job stats are exclusively used for job tracing [purposes](https://github.com/rivosinc/prometheus-slurm-exporter?tab=readme-ov-file#job-tracing). If you aren't running a tracing wrapper, then no data will show up.
